import React from 'react';
import { ShieldAlert, Compass, FileSpreadsheet, Radio, Check, Lock } from 'lucide-react';

export const TrustSection: React.FC = () => {
  const trustPillars = [
    {
      id: 'explainability',
      icon: Compass,
      title: 'Explainable Decisions & Alternatives',
      badge: 'TRANSPARENT DISPATCH',
      badgeColor: 'border-amber-500/30 text-amber-400 bg-amber-500/10',
      description:
        'Every dispatch setpoint generated by SURYA is accompanied by plain-language human-readable justifications, explicit mathematical formulas, and counter-factual evaluations of rejected alternative setpoints.',
      highlights: [
        'Plain-language operator rationale',
        'Mathematical formulas exposed per step',
        'Evaluated rejected alternatives with score differential',
        'Auditable decision trail in immutable log',
      ],
    },
    {
      id: 'estop',
      icon: ShieldAlert,
      title: 'Production Emergency Stop with Mandatory Audit',
      badge: 'FAIL-SAFE INTERLOCK',
      badgeColor: 'border-red-500/30 text-red-400 bg-red-500/10',
      description:
        'A physical-grade closed-loop emergency stop interlock freezes all active inverter setpoints instantaneously. Unlocking or executing an emergency stop requires authenticated role-based access and mandatory audit justifications.',
      highlights: [
        'Instant inverter setpoint freeze to neutral safe state',
        'Mandatory justification logging for operators',
        'Argon2id and role-governed authorization',
        'Automated alarm broadcast across all client terminals',
      ],
    },
    {
      id: 'esg-reporting',
      icon: FileSpreadsheet,
      title: 'RFC 4180 ESG Compliance & PDF Exports',
      badge: 'DATA QUALITY DISCLOSURE',
      badgeColor: 'border-emerald-500/30 text-emerald-400 bg-emerald-500/10',
      description:
        'Generates RFC 4180 standard CSV spreadsheets and executive PDF reports with explicit data quality disclosures, staleness indicators, and baseline comparisons against CEA carbon emission factors.',
      highlights: [
        'Strict RFC 4180 compliance with CRLF line terminators',
        'Executive PDF downloads rendered via ReportLab',
        'Zero-fill detection and staleness metrics included',
        'Time-of-Day savings and carbon avoidance breakdown',
      ],
    },
    {
      id: 'websocket-stream',
      icon: Radio,
      title: 'Real-Time WebSocket Streaming & Backoff',
      badge: 'SUB-SECOND RESILIENCE',
      badgeColor: 'border-emerald-500/30 text-emerald-400 bg-emerald-500/10',
      description:
        'Sub-second live digital twin telemetry updates, alarm push notifications, and full-cycle dispatch broadcasts. Built with resilient auto-reconnection and exponential backoff.',
      highlights: [
        'Sub-second bidirectional broadcast protocol',
        'Exponential backoff reconnection handler',
        'Real-time alarm and alert dispatching',
        'Connection health monitoring with visual state indicators',
      ],
    },
  ];

  return (
    <section id="trust-section" className="relative bg-heritage-page py-24 sm:py-32 overflow-hidden">
      <div className="section-divider section-divider-top" />

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16 sm:mb-20">
          <div className="gsap-reveal heritage-badge mb-4 backdrop-blur-md">
            <Lock className="h-3.5 w-3.5" />
            <span>OPERATIONAL TRUST & AUDIT INTEGRITY</span>
          </div>
          <h2 data-anim="split-heading" className="gsap-reveal font-display text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-white">
            Zero Black-Box Decisions
          </h2>
          <p className="gsap-reveal mt-4 text-base sm:text-lg text-slate-400 font-sans">
            Autonomous dispatch without transparency creates liability. SURYA guarantees every optimization
            decision is verifiable, explainable, and interruptible by campus facility engineers.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 lg:gap-8">
          {trustPillars.map((pillar) => {
            const Icon = pillar.icon;
            return (
              <div
                key={pillar.id}
                data-anim="card"
                className="gsap-reveal heritage-main-card p-6 sm:p-8 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-5">
                    <div className="heritage-inner-card !p-0 flex h-12 w-12 items-center justify-center text-heritage-accent">
                      <Icon className="h-6 w-6" />
                    </div>
                    <span className="heritage-badge">
                      {pillar.badge}
                    </span>
                  </div>

                  <h3 className="heritage-heading text-xl sm:text-2xl font-bold tracking-tight">
                    {pillar.title}
                  </h3>
                  <p className="heritage-body mt-3 text-sm leading-relaxed">
                    {pillar.description}
                  </p>

                  <div className="mt-6 pt-6 border-t heritage-divider space-y-2.5">
                    {pillar.highlights.map((item, idx) => (
                      <div key={idx} className="flex items-start gap-2.5 text-xs text-heritage-text-secondary">
                        <Check className="h-4 w-4 text-heritage-accent shrink-0 mt-0.5" />
                        <span>{item}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <div className="section-divider section-divider-bottom" />
    </section>
  );
};
